import sys

sys.path.append('/home/kristian/UAF_auction')
from uaf import app as application
from event_prefill import register_routes as register_event_prefill_routes
from extra_labels import register_routes as register_extra_label_routes
from label_preview import register_routes as register_label_preview_routes
from payment_records import register_routes as register_payment_routes
from payment_report_pdf import register_routes as register_payment_report_routes
from password_reset import register_routes as register_password_reset_routes
from post_limit import register_routes as register_post_limit_routes
from swish_qr import register_routes as register_swish_qr_routes

register_label_preview_routes(application)
register_post_limit_routes(application)
register_extra_label_routes(application)
register_payment_routes(application)
register_payment_report_routes(application)
register_password_reset_routes(application)
register_event_prefill_routes(application)
register_swish_qr_routes(application)